#!/bin/bash

if git rev-parse --verify HEAD >/dev/null 2>&1; then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=$(git hash-object -t tree /dev/null)
fi

# Redirect output to stderr.
exec 1>&2

REMOTE_ORIGIN_URL=$(git config --local remote.origin.url)
git_domain="git"
git_user_name="flap1"
git_user_email="sho1seto@gmail.com"

local_git_user_name=$(git config --local user.name)
local_git_user_email=$(git config --local user.email)

readonly REMOTE_ORIGIN_URL
readonly git_domain
readonly git_user_name
readonly git_user_email
readonly local_git_user_name
readonly local_git_user_email

# Check if the Author has been changed
if [[ "${git_user_name}" != "${local_git_user_name}" ]] || [[ "${git_user_email}" != "${local_git_user_email}" ]]; then
    # Change the Author to company information
    if [[ "${REMOTE_ORIGIN_URL}" = *"${git_domain}"* ]]; then
        git config --local user.name "${git_user_name}"
        git config --local user.email "${git_user_email}"
        git reset HEAD . # Because you can't change the Author of staged files
        echo "[WARN] Configure the Author (name, email) and unstage files." >&2
        echo "[WARN] Please run git-commands again." >&2
        exit 1
    fi
fi

# Warn if there are unresolved conflict files
while IFS= read -r file; do
    if [[ ! -e "$file" ]]; then
        # Skip deleted files
        continue
    fi
    grep_result=$(grep -E '(<<<<<<<|>>>>>>>)' "$file" | grep -v '^$')
    if [[ -n "${grep_result}" ]]; then
        echo $'\e[1;31m'"$file"$'\e[m' ' <- There are conflicting unresolved files'
        echo "$grep_result"
        exit 1
    fi
done < <(git diff-index --name-status "$against" | grep -E '\.(swift|pbxproj|m|h|xib|storyboard)$' | cut -c3-)
