---

# This is the top level remark configuration file. You may need to make a local
# copy to override settings at a project level.

# To install all the required plugins:
#
#   npm i -g $(grep remark-lint ~/.remarkrc.yml | \
#       sed -e '/\s*#/d' -e 's/^  - \(- \)\?//')

# These 'settings' affect the `remark-stringify` formater, not the linter, and
# are mostly covered in https://github.com/syntax-tree/mdast-util-to-markdown
settings:

  # Markers (all set to defaults)
  bullet: '*'
  fence: '`'
  strong: '*'
  emphasis: '*'

  # Use a different marker for contrast
  rule: '-'

  # Always use fences for code blocks to match Markdown Style Guide (MSG)
  fences: true

  # Indent the content of list items with the size of the bullet plus one space
  # For consistency with editor settings
  listItemIndent: one

  # Personal preference: draw a long line of dashes for a thematic break
  ruleRepetition: 80


plugins:
  # --- Processfrontmatter -------------------------------------#
  # Ignore intial frontmatter in 
  # See https://github.com/micromark/micromark-extension-frontmatter
  - remark-frontmatter

