let g:vimtex_view_general_viewer = 'okular'
let g:vimtex_view_general_options = '--unique file:@pdf\#src:@line@tex'

let g:vimtex_compiler_latexmk = {
      \ 'build_dir' : 'out',
      \ 'options' : [
      \   '-pdfdvi',
      \   '-verbose',
      \   '-file-line-error',
      \   '-synctex=1',
      \   '-interaction=nonstopmode',
      \ ]}

" nmap <LocalLeader>li <plug>(vimtex-info)
" nmap <LocalLeader>lI <plug>(vimtex-info-full)
" nmap <localleader>lt <plug>(vimtex-toc-open)
" nmap <localleader>lT <plug>(vimtex-toc-toggle)
" nmap <localleader>lq <plug>(vimtex-log)
" nmap <localleader>lv <plug>(vimtex-view)
" nmap <localleader>lr <plug>(vimtex-reverse-search)
" nmap <LocalLeader>ll <plug>(vimtex-compile)
" nmap <localleader>lL <plug>(vimtex-compile-selected)
" xmap <localleader>lL <plug>(vimtex-compile-selected)
" nmap <localleader>lk <plug>(vimtex-stop)
" nmap <localleader>lK <plug>(vimtex-stop-all)
" nmap <localleader>le <plug>(vimtex-errors)
" nmap <localleader>lo <plug>(vimtex-compile-output)
" nmap <localleader>lg <plug>(vimtex-status)
" nmap <localleader>lG <plug>(vimtex-status-all)
" nmap <localleader>lc <plug>(vimtex-clean)
" nmap <localleader>lC <plug>(vimtex-clean-full)
" nmap <localleader>lm <plug>(vimtex-imaps-list)
" nmap <localleader>lx <plug>(vimtex-reload)
" nmap <localleader>lX <plug>(vimtex-reload-state)
" nmap <localleader>ls <plug>(vimtex-toggle-main)
" nmap <localleader>la <plug>(vimtex-context-menu)
" autocmd FileType tex nnoremap <buffer> dse <plug>(vimtex-env-delete)
" autocmd FileType tex nnoremap <buffer> dsc <plug>(vimtex-cmd-delete)
" autocmd FileType tex nnoremap <buffer> ds$ <plug>(vimtex-env-delete-math)
" autocmd FileType tex nnoremap <buffer> dsd <plug>(vimtex-delim-delete)
" autocmd FileType tex nnoremap <buffer> cse <plug>(vimtex-env-change)
" autocmd FileType tex nnoremap <buffer> csc <plug>(vimtex-cmd-change)
" autocmd FileType tex nnoremap <buffer> cs$ <plug>(vimtex-env-change-math)
" autocmd FileType tex nnoremap <buffer> csd <plug>(vimtex-delim-change-math)
" autocmd FileType tex nnoremap <buffer> tsf <plug>(vimtex-cmd-toggle-frac)
" autocmd FileType tex xnoremap <buffer> tsf <plug>(vimtex-cmd-toggle-frac)
" autocmd FileType tex nnoremap <buffer> tsc <plug>(vimtex-cmd-toggle-star)
" autocmd FileType tex nnoremap <buffer> tse <plug>(vimtex-env-toggle-star)
" autocmd FileType tex nnoremap <buffer> ts$ <plug>(vimtex-env-toggle-math)
" autocmd FileType tex nnoremap <buffer> tsd <plug>(vimtex-delim-toggle-modifier)
" autocmd FileType tex xnoremap <buffer> tsd <plug>(vimtex-delim-toggle-modifier)
" autocmd FileType tex nnoremap <buffer> tsD <plug>(vimtex-delim-toggle-modifier-reverse)
" autocmd FileType tex xnoremap <buffer> tsD <plug>(vimtex-delim-toggle-modifier-reverse)
" autocmd FileType tex inoremap <buffer> ]]  <plug>(vimtex-delim-close)
" autocmd FileType tex xnoremap <buffer> ac  <plug>(vimtex-ac)
" autocmd FileType tex xnoremap <buffer> ic  <plug>(vimtex-ic)
" autocmd FileType tex xnoremap <buffer> ad  <plug>(vimtex-ad)
" autocmd FileType tex xnoremap <buffer> id  <plug>(vimtex-id)
" autocmd FileType tex xnoremap <buffer> ae  <plug>(vimtex-ae)
" autocmd FileType tex xnoremap <buffer> ie  <plug>(vimtex-ie)
" autocmd FileType tex xnoremap <buffer> a$  <plug>(vimtex-a$)
" autocmd FileType tex xnoremap <buffer> i$  <plug>(vimtex-i$)
" autocmd FileType tex xnoremap <buffer> aP  <plug>(vimtex-aP)
" autocmd FileType tex xnoremap <buffer> iP  <plug>(vimtex-iP)
" autocmd FileType tex xnoremap <buffer> am  <plug>(vimtex-am)
" autocmd FileType tex xnoremap <buffer> im  <plug>(vimtex-im)
" autocmd FileType tex onoremap <buffer> ac  <plug>(vimtex-ac)
" autocmd FileType tex onoremap <buffer> ic  <plug>(vimtex-ic)
" autocmd FileType tex onoremap <buffer> ad  <plug>(vimtex-ad)
" autocmd FileType tex onoremap <buffer> id  <plug>(vimtex-id)
" autocmd FileType tex onoremap <buffer> ae  <plug>(vimtex-ae)
" autocmd FileType tex onoremap <buffer> ie  <plug>(vimtex-ie)
" autocmd FileType tex onoremap <buffer> a$  <plug>(vimtex-a$)
" autocmd FileType tex onoremap <buffer> i$  <plug>(vimtex-i$)
" autocmd FileType tex onoremap <buffer> aP  <plug>(vimtex-aP)
" autocmd FileType tex onoremap <buffer> iP  <plug>(vimtex-iP)
" autocmd FileType tex onoremap <buffer> am  <plug>(vimtex-am)
" autocmd FileType tex onoremap <buffer> im  <plug>(vimtex-im)
" autocmd FileType tex nnoremap <buffer> %   <plug>(vimtex-%)
" autocmd FileType tex nnoremap <buffer> ]]  <plug>(vimtex-]])
" autocmd FileType tex nnoremap <buffer> ][  <plug>(vimtex-][)
" autocmd FileType tex nnoremap <buffer> []  <plug>(vimtex-[])
" autocmd FileType tex nnoremap <buffer> [[  <plug>(vimtex-[[)
" autocmd FileType tex nnoremap <buffer> ]m  <plug>(vimtex-]m)
" autocmd FileType tex nnoremap <buffer> ]M  <plug>(vimtex-]M)
" autocmd FileType tex nnoremap <buffer> [m  <plug>(vimtex-[m)
" autocmd FileType tex nnoremap <buffer> [M  <plug>(vimtex-[M)
" autocmd FileType tex nnoremap <buffer> ]n  <plug>(vimtex-]n)
" autocmd FileType tex nnoremap <buffer> ]N  <plug>(vimtex-]N)
" autocmd FileType tex nnoremap <buffer> [n  <plug>(vimtex-[n)
" autocmd FileType tex nnoremap <buffer> [N  <plug>(vimtex-[N)
" autocmd FileType tex nnoremap <buffer> ]r  <plug>(vimtex-]r)
" autocmd FileType tex nnoremap <buffer> ]R  <plug>(vimtex-]R)
" autocmd FileType tex nnoremap <buffer> [r  <plug>(vimtex-[r)
" autocmd FileType tex nnoremap <buffer> [R  <plug>(vimtex-[R)
" autocmd FileType tex nnoremap <buffer> ]/  <plug>(vimtex-]/)
" autocmd FileType tex nnoremap <buffer> ]*  <plug>(vimtex-]star)
" autocmd FileType tex nnoremap <buffer> [/  <plug>(vimtex-[/)
" autocmd FileType tex nnoremap <buffer> [*  <plug>(vimtex-[star)
" autocmd FileType tex xnoremap <buffer> %   <plug>(vimtex-%)
" autocmd FileType tex xnoremap <buffer> ]]  <plug>(vimtex-]])
" autocmd FileType tex xnoremap <buffer> ][  <plug>(vimtex-][)
" autocmd FileType tex xnoremap <buffer> []  <plug>(vimtex-[])
" autocmd FileType tex xnoremap <buffer> [[  <plug>(vimtex-[[)
" autocmd FileType tex xnoremap <buffer> ]m  <plug>(vimtex-]m)
" autocmd FileType tex xnoremap <buffer> ]M  <plug>(vimtex-]M)
" autocmd FileType tex xnoremap <buffer> [m  <plug>(vimtex-[m)
" autocmd FileType tex xnoremap <buffer> [M  <plug>(vimtex-[M)
" autocmd FileType tex xnoremap <buffer> ]n  <plug>(vimtex-]n)
" autocmd FileType tex xnoremap <buffer> ]N  <plug>(vimtex-]N)
" autocmd FileType tex xnoremap <buffer> [n  <plug>(vimtex-[n)
" autocmd FileType tex xnoremap <buffer> [N  <plug>(vimtex-[N)
" autocmd FileType tex xnoremap <buffer> ]r  <plug>(vimtex-]r)
" autocmd FileType tex xnoremap <buffer> ]R  <plug>(vimtex-]R)
" autocmd FileType tex xnoremap <buffer> [r  <plug>(vimtex-[r)
" autocmd FileType tex xnoremap <buffer> [R  <plug>(vimtex-[R)
" autocmd FileType tex xnoremap <buffer> ]/  <plug>(vimtex-]/)
" autocmd FileType tex xnoremap <buffer> ]*  <plug>(vimtex-]star)
" autocmd FileType tex xnoremap <buffer> [/  <plug>(vimtex-[/)
" autocmd FileType tex xnoremap <buffer> [*  <plug>(vimtex-[star)
" autocmd FileType tex onoremap <buffer> %   <plug>(vimtex-%)
" autocmd FileType tex onoremap <buffer> ]]  <plug>(vimtex-]])
" autocmd FileType tex onoremap <buffer> ][  <plug>(vimtex-][)
" autocmd FileType tex onoremap <buffer> []  <plug>(vimtex-[])
" autocmd FileType tex onoremap <buffer> [[  <plug>(vimtex-[[)
" autocmd FileType tex onoremap <buffer> ]m  <plug>(vimtex-]m)
" autocmd FileType tex onoremap <buffer> ]M  <plug>(vimtex-]M)
" autocmd FileType tex onoremap <buffer> [m  <plug>(vimtex-[m)
" autocmd FileType tex onoremap <buffer> [M  <plug>(vimtex-[M)
" autocmd FileType tex onoremap <buffer> ]n  <plug>(vimtex-]n)
" autocmd FileType tex onoremap <buffer> ]N  <plug>(vimtex-]N)
" autocmd FileType tex onoremap <buffer> [n  <plug>(vimtex-[n)
" autocmd FileType tex onoremap <buffer> [N  <plug>(vimtex-[N)
" autocmd FileType tex onoremap <buffer> ]r  <plug>(vimtex-]r)
" autocmd FileType tex onoremap <buffer> ]R  <plug>(vimtex-]R)
" autocmd FileType tex onoremap <buffer> [r  <plug>(vimtex-[r)
" autocmd FileType tex onoremap <buffer> [R  <plug>(vimtex-[R)
" autocmd FileType tex onoremap <buffer> ]/  <plug>(vimtex-]/)
" autocmd FileType tex onoremap <buffer> ]*  <plug>(vimtex-]star)
" autocmd FileType tex onoremap <buffer> [/  <plug>(vimtex-[/)
" autocmd FileType tex onoremap <buffer> [*  <plug>(vimtex-[star)
" autocmd FileType tex nnoremap <buffer> K   <plug>(vimtex-doc-package)
