#!/usr/bin/env bash
# gen-keymaps.sh
# Generate KEYMAPS.md from dotfiles configuration files.
# Usage: bash scripts/gen-keymaps.sh [output_file]
# Default output: KEYMAPS.md in the repo root.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUTPUT="${1:-${REPO_ROOT}/KEYMAPS.md}"
DATE="$(date +%Y-%m-%d)"

cat > "$OUTPUT" << 'HEREDOC'
# Keymaps Reference
HEREDOC

# Append generated date
echo "<!-- Auto-generated by scripts/gen-keymaps.sh on ${DATE} -->" >> "$OUTPUT"
echo "<!-- Manual edits will be overwritten. Edit the source config files instead. -->" >> "$OUTPUT"
echo "" >> "$OUTPUT"

cat >> "$OUTPUT" << 'HEREDOC'
## Key Notation

| Symbol | Meaning |
|--------|---------|
| `<Leader>` | Space |
| `<LocalLeader>` | `,` |
| `<M->` | Alt/Option |
| `<C->` | Ctrl |
| `<S->` | Shift |
| `[n]` | Normal mode |
| `[i]` | Insert mode |
| `[v]` | Visual mode |
| `[x]` | Visual only (not Select) |
| `[o]` | Operator-pending mode |
| `[t]` | Terminal mode |
| `[c]` | Command-line mode |

---

## Tmux

**Prefix: `C-\` (Ctrl + Backslash)**

### Global (no Prefix)

| Key | Action | Description |
|-----|--------|-------------|
| `C-l` | `send-keys C-l; clear-history` | Clear screen and scrollback history |
| `Prefix m` | toggle `mouse on/off` | Toggle mouse |

### Session

| Key | Action | Description |
|-----|--------|-------------|
| `Prefix C-c` | `new-session` | Create new session |
| `Prefix c` | `new-session` | Create new session |
| `Prefix C-f` | `command-prompt find-session` | Find and switch session |
| `Prefix BTab` | `switch-client -l` | Switch to last session |

### Windows

| Key | Action | Description |
|-----|--------|-------------|
| `Prefix C-n` | `new-window` | New window |
| `Prefix n` | `new-window` | New window |
| `Prefix C-h` | `previous-window` | Previous window |
| `Prefix C-l` | `next-window` | Next window |
| `Prefix Tab` | `last-window` | Last used window |
| `Prefix C-q` | `confirm-before kill-window` | Kill window (with confirm) |
| `Prefix q` | `confirm-before kill-window` | Kill window (with confirm) |

### Panes

| Key | Action | Description |
|-----|--------|-------------|
| `Prefix -` | `split-window -v` | Split horizontally (top/bottom) |
| `Prefix \|` | `split-window -h` | Split vertically (left/right) |
| `Prefix h` (repeat) | `select-pane -L` | Move to left pane |
| `Prefix j` (repeat) | `select-pane -D` | Move to bottom pane |
| `Prefix k` (repeat) | `select-pane -U` | Move to top pane |
| `Prefix l` (repeat) | `select-pane -R` | Move to right pane |
| `Prefix >` | `swap-pane -D` | Swap pane with next |
| `Prefix <` | `swap-pane -U` | Swap pane with previous |
| `Prefix +` | `resize-pane -Z` | Zoom/unzoom current pane |
| `Prefix H` (repeat) | `resize-pane -L 5` | Resize pane left |
| `Prefix J` (repeat) | `resize-pane -D 5` | Resize pane down |
| `Prefix K` (repeat) | `resize-pane -U 5` | Resize pane up |
| `Prefix L` (repeat) | `resize-pane -R 5` | Resize pane right |

### Other

| Key | Action | Description |
|-----|--------|-------------|
| `Prefix r` | `source-file ~/.tmux.conf` | Reload tmux config |
| `Prefix w` (repeat) | `choose-tree -w` | Show window tree |
| `Prefix t` (repeat) | `clock-mode` | Show clock |

**Plugins:** tpm, tmux-sensible, tmux-resurrect, tmux-continuum (auto-restore), tmux-cpu, catppuccin/tmux (mocha)

---

## WezTerm

### Normal Mode

| Mods | Key | Action |
|------|-----|--------|
| `ALT` | `Enter` | Toggle fullscreen |
| `CTRL+SHIFT` | `r` | Reload configuration |
| `CTRL+SHIFT` | `=` | Reset font size |
| `CTRL` | `=` | Reset font size |
| `CTRL+SHIFT` | `+` | Increase font size |
| `CTRL` | `+` | Increase font size |
| `CTRL` | `-` | Decrease font size |
| `ALT+CTRL` | `1`-`9` | Activate tab N |
| `CTRL` | `Tab` | Next tab |
| `CTRL+SHIFT` | `Tab` | Previous tab |
| `ALT+CTRL` | `h` | Move tab left |
| `ALT+CTRL` | `l` | Move tab right |
| `ALT+CTRL` | `j` | Previous tab |
| `ALT+CTRL` | `k` | Next tab |
| `ALT+CTRL` | `n` | New tab |
| `ALT+CTRL` | `-` | Split pane vertically |
| `ALT+CTRL` | `\` | Split pane horizontally |
| `ALT+CTRL` | `h/j/k/l` | Activate pane (Left/Down/Up/Right) |
| `ALT+CTRL` | `r` | Enter resize_pane mode (1s timeout) |
| `ALT+CTRL` | `s` | Select pane by number |
| `ALT+CTRL` | `b` | Rotate panes counter-clockwise |
| `ALT+CTRL` | `f` | Rotate panes clockwise |
| `CTRL+SHIFT` | `c` | Copy to clipboard |
| `CTRL+SHIFT` | `v` | Paste from clipboard |
| `CTRL+ALT` | `c` | Activate copy mode |
| `CTRL+ALT` | `Enter` | Activate copy mode |
| `CTRL+ALT` | `q` | Close current pane (with confirm) |

### resize_pane Mode (activated by ALT+CTRL+r, 1s timeout)

| Key | Action |
|-----|--------|
| `h` / `LeftArrow` | Resize pane left |
| `l` / `RightArrow` | Resize pane right |
| `k` / `UpArrow` | Resize pane up |
| `j` / `DownArrow` | Resize pane down |
| `Escape` | Exit resize mode |

### copy_mode

| Key | Action |
|-----|--------|
| `Escape` / `q` | Close copy mode |
| `h/j/k/l` | Move cursor |
| `Arrow keys` | Move cursor |
| `w` / `Tab` | Move forward word |
| `b` / `Shift+Tab` | Move backward word |
| `0` | Move to start of line |
| `^` | Move to first non-blank |
| `$` | Move to end of line |
| `v` | Start cell selection |
| `Shift+v` | Select whole line |
| `y` | Copy selection and close |
| `Shift+y` | Copy to end of line and close |
| `g` | Move to scrollback top |
| `G` | Move to scrollback bottom |
| `H/M/L` | Move to viewport top/middle/bottom |
| `o` / `O` | Move to other end of selection |
| `PageUp` / `C-b` | Page up |
| `PageDown` / `C-f` | Page down |
| `/` | Search |
| `n` / `N` | Next / previous match |

---

## Neovim

**Leader: `Space`** | **LocalLeader: `,`**

### Core — Save / Quit [n]

| Key | Action |
|-----|--------|
| `<Leader>w` | Save file |
| `<Leader>q` | Quit |
| `<Leader>aq` | Quit all |
| `<Leader>aw` | Save all |
| `<M-w>` | Save file |
| `<M-q>` | Quit |

### Core — Escape [i][t]

| Key | Mode | Action |
|-----|------|--------|
| `jk` | Insert | Escape |
| `ｊｋ` | Insert | Escape (Japanese IME) |
| `jk` | Terminal | Exit terminal mode |
| `<C-[>` | Terminal | Exit terminal mode |

### Core — Movement [n]

| Key | Action |
|-----|--------|
| `H` / `L` | Move 5 chars left / right |
| `j` / `k` | Smart line movement (respects word wrap) |
| `gH` / `gM` / `gL` | Screen top / middle / bottom |
| `(` / `)` / `[[` / `]]` | Paragraph / section jump (centered) |
| `^` | Toggle between `^` and `0` |
| `$` | Toggle between `$` and `g_` |
| `n` / `N` | Smart search next/prev (centered) |
| `*` / `#` | Search current word (no jump) |
| `gq` | Clear search highlight |
| `Escape` | Clear search highlight + redraw |

### Core — Editing [n]

| Key | Action |
|-----|--------|
| `<C-x>` | Indent right (in normal mode) |
| `<C-z>` | Indent left |
| `<C-t>` (insert) | Swap last two characters |
| `d<Space>` / `c<Space>` / `y<Space>` | Delete/change/yank inner word |
| `gy` | Yank to end (visual friendly) |
| `<LocalLeader>y` | Yank to register 0 |
| `<LocalLeader>p` / `<LocalLeader>P` | Paste from register 0 |
| `<LocalLeader>x` / `<LocalLeader>d` / `<LocalLeader>D` | Delete to void register |
| `<LocalLeader>c` / `<LocalLeader>C` | Change to void register |
| `^` | Jump to older change position (g;) |
| `&` | Jump to newer change position (g,) |
| `i` / `A` (on blank line) | Auto-indent on empty line |

### Core — Buffer [n]

| Key | Action |
|-----|--------|
| `[b` / `]b` | Previous / next buffer |
| `[B` / `]B` | First / last buffer |

### Core — Window [n]

| Key | Action |
|-----|--------|
| `<C-h/j/k/l>` | Move to window (smart-splits) |
| `<M-h/j/k/l>` | Resize window (smart-splits) |
| `<M-o>` | Close all other windows |
| `;1` - `;9` | Go to window N |
| `-` | Horizontal split |
| `\` | Vertical split |

### Core — Tab [n]

| Key | Action |
|-----|--------|
| `<LocalLeader>1`-`9` | Go to tab N |
| `<M-t>j` | Previous tab |
| `<M-t>k` | Next tab |
| `<M-t>J` | Move tab left |
| `<M-t>K` | Move tab right |
| `<M-t>q` | Close tab |
| `<M-t>n` | New tab |

### Core — Search / Replace [n][x]

| Key | Mode | Action |
|-----|------|--------|
| `/` / `?` | n,x | Very magic regex search |
| `<LocalLeader>s` | n | Substitute word under cursor |
| `<LocalLeader>s` | x | Substitute in visual selection |
| `;s` | n | `:%s/\v` substitute command |
| `[q` / `]q` | n | Previous / next quickfix |
| `[Q` / `]Q` | n | First / last quickfix |
| `[l` / `]l` | n | Previous / next location list |
| `;q` | n | Toggle quickfix |

### Core — Emacs-style [i][c][t]

| Key | Action |
|-----|--------|
| `<C-a>` / `<C-e>` | Move to line start / end |
| `<C-b>` / `<C-f>` | Move back / forward char |
| `<C-p>` / `<C-n>` | Move up / down |
| `<C-d>` / `<C-h>` | Delete forward / backward char |
| `<M-b>` | Move back word |

### Core — Encoding [n]

| Key | Action |
|-----|--------|
| `<LocalLeader>eu` | Set encoding to utf-8 |
| `<LocalLeader>es` | Set encoding to shift-jis |
| `<LocalLeader>ee` | Set encoding to euc-jp |
| `<LocalLeader>ej` | Set encoding to iso-2022-jp |

### Core — Misc [n]

| Key | Action |
|-----|--------|
| `<LocalLeader><CR>` | Reload vimrc |
| `<LocalLeader>cd` | Change cwd to current file's dir |
| `<LocalLeader>-` | Fill line with dashes (to col 50) |
| `gx` | Open URL under cursor in browser |
| `g<CR>` | WhichKey: show `g` group |
| `[<CR>` / `]<CR>` | WhichKey: show `[` / `]` group |

---

### LSP [n][x]

| Key | Mode | Action |
|-----|------|--------|
| `gD` | n | Go to declaration |
| `gd` | n | Go to definition |
| `?` | n | Hover documentation |
| `gi` | n | Go to implementation |
| `g?` | n | Signature help |
| `;D` | n | Go to type definition |
| `;a` | n | Code action |
| `;r` | n | Rename symbol |
| `gr` | n | Find references |
| `;e` | n | Show diagnostics float |
| `[d` / `]d` | n | Previous / next diagnostic |
| `;f` | n,x | Format buffer (conform.nvim) |
| `;;f` | n,x | Format buffer (alt binding) |

---

### Diagnostics / Trouble [n]

| Key | Action |
|-----|--------|
| `<Leader>xx` | Toggle diagnostics (Trouble) |
| `<Leader>xX` | Toggle buffer diagnostics (Trouble) |
| `<Leader>xq` | Toggle quickfix in Trouble |

---

### Git [n][v]

#### Gitsigns

| Key | Mode | Action |
|-----|------|--------|
| `]h` / `[h` | n | Next / previous hunk |
| `<Leader>hs` | n,v | Stage hunk |
| `<Leader>hr` | n,v | Reset hunk |
| `<Leader>hS` | n | Stage buffer |
| `<Leader>hu` | n | Undo stage hunk |
| `<Leader>hR` | n | Reset buffer |
| `<Leader>hp` | n | Preview hunk |
| `<Leader>hb` | n | Blame line |
| `<Leader>hB` | n | Toggle line blame |
| `<Leader>hd` | n | Diff this |
| `<Leader>hD` | n | Diff against parent commit |
| `ih` | o,x | Select hunk (text object) |

#### Neogit / Diffview

| Key | Action |
|-----|--------|
| `<Leader>gg` | Open Neogit |
| `<Leader>gd` | Open Diffview |
| `<Leader>gD` | Close Diffview |
| `<Leader>gh` | File history (Diffview) |

---

### Telescope [n][i][t]

| Key | Action |
|-----|--------|
| `<M-p>` | Project picker |
| `<M-b>` | Bookmarks |
| `<M-f>x` | Find files (no dotfiles) |
| `<M-f>e` | Frecency file picker |
| `<M-f>u` | Unicode symbols |
| `<M-f>j` | Live grep |
| `<M-f>f` | Find all files |
| `<M-f><Leader>` | Buffers |
| `<M-f>@` | BibTeX |
| `<M-f>c` | Command history |
| `<M-f>h` | Help tags |
| `<M-f>t` | Treesitter symbols |
| `<M-f>o` | Old files |
| `<M-f>k` | Keymaps |
| `<M-f>m` | Marks |
| `<M-f>/` | Search history |
| `<M-f>r` | Registers |
| `<M-f>q` | Quickfix list |
| `<M-f>l` | Location list |
| `<M-f>s` | Session list (possession) |
| `<M-f>;` | Git files |
| `<M-f>b` | File browser |
| `<M-f>a` | Repo list |
| `<M-f>gc` | Git commits |
| `<M-f>gs` | Git status |
| `<M-f>gC` | File git commits |
| `<M-f>gb` | Git branches |
| `<C-p>` | Project picker (alt) |
| `"` | Registers (alt) |
| `<Leader>"` | Clipboard history (neoclip) |

#### Inside Telescope

| Key | Action |
|-----|--------|
| `Escape` / `<Leader>q` | Close |
| `<M-p>` | Toggle preview |
| `<C-space>` | Multi-select → send to quickfix |

---

### Editing Plugins

#### Flash.nvim [n][x][o]

| Key | Mode | Action |
|-----|------|--------|
| `s` | n,x,o | Flash jump |
| `S` | n,x,o | Flash Treesitter jump |
| `r` | o | Remote flash |
| `R` | o,x | Treesitter search |
| `<C-s>` | c | Toggle flash search |

> Flash also handles `f/F/t/T` with jump labels enabled.

#### nvim-surround [n][x][i]

| Key | Mode | Action |
|-----|------|--------|
| `ys{motion}{char}` | n | Add surrounding |
| `yss{char}` | n | Surround current line |
| `cs{old}{new}` | n | Change surrounding |
| `ds{char}` | n | Delete surrounding |
| `s` | x | Visual surround |
| `<C-s>` | i | Insert surround |

#### dial.nvim [n][v]

| Key | Action |
|-----|--------|
| `<C-a>` | Increment (int, hex, date, bool, semver) |
| `<C-x>` | Decrement |
| `g<C-a>` | Increment (visual, gnormal) |
| `g<C-x>` | Decrement (visual, gnormal) |

#### fold-cycle.nvim [n]

| Key | Action |
|-----|--------|
| `<Tab>` | Open fold |
| `<S-Tab>` | Close fold |
| `zC` | Close all folds |

#### treesj (split/join) [n]

| Key | Action |
|-----|--------|
| `<LocalLeader>j` | Toggle split/join block |

#### substitute.nvim [n][x]

| Key | Mode | Action |
|-----|------|--------|
| `U` | n | Substitute with motion |
| `Uu` | n | Substitute line |
| `UU` | n | Substitute to end of line |
| `U` | x | Substitute visual selection |

#### nvim-treesitter-textobjects [n][x][o]

| Key | Mode | Action |
|-----|------|--------|
| `af` / `if` | x,o | Around / inner function |
| `ac` / `ic` | x,o | Around / inner class |
| `aa` / `ia` | x,o | Around / inner parameter |
| `]f` / `[f` | n | Next / prev function start |
| `]c` / `[c` | n | Next / prev class start |
| `<LocalLeader>a` | n | Swap with next parameter |
| `<LocalLeader>A` | n | Swap with previous parameter |

#### nvim-treehopper [o][x]

| Key | Mode | Action |
|-----|------|--------|
| `m` | o,x | Select treesitter node |

#### Harpoon [n]

| Key | Action |
|-----|--------|
| `<Leader>Ha` | Add file to Harpoon |
| `<Leader>Hh` | Toggle Harpoon quick menu |
| `<C-1>` - `<C-5>` | Jump to Harpoon file 1-5 |

#### Translate.nvim [n][x]

| Key | Action |
|-----|--------|
| `<Leader>tj` | Translate to Japanese |
| `<Leader>te` | Translate to English |

#### replacer.nvim [n]

| Key | Action |
|-----|--------|
| `<Leader>h` | Edit quickfix as buffer (replacer) |

#### CamelCaseMotion [n][x][o]

| Key | Action |
|-----|--------|
| `<Leader>w` | CamelCase forward word |
| `<Leader>b` | CamelCase backward word |
| `<Leader>e` | CamelCase end of word |

#### vim-asterisk [n][x]

| Key | Action |
|-----|--------|
| `*` | Search current word (no jump, centered) |
| `#` | Search current word backward (no jump) |

---

### Terminal (Toggleterm) [n][i][t]

| Key | Action |
|-----|--------|
| `<M-a>` | Toggle all terminals |
| `<M-0>` | Toggle default terminal |
| `<M-1>` - `<M-5>` | Open terminal 1-5 |
| `jk` (in terminal) | Exit terminal insert mode |

---

### UI

#### Bufferline [n]

| Key | Action |
|-----|--------|
| `<M-,>` | Previous buffer |
| `<M-.>` | Next buffer |
| `<M-<>` | Move buffer left |
| `<M->>` | Move buffer right |
| `<Leader>1` - `<Leader>9` | Go to buffer N |

#### Neo-tree [n]

| Key | Action |
|-----|--------|
| `<M-n>` | Toggle Neo-tree |
| `<M-N>` | Reveal current file in Neo-tree |

#### Oil.nvim [n]

| Key | Action |
|-----|--------|
| `-` | Open Oil file browser |

#### Yazi [n]

| Key | Action |
|-----|--------|
| `<Leader>fy` | Open Yazi (current file dir) |
| `<Leader>fY` | Open Yazi (cwd) |

#### Todo-comments [n]

| Key | Action |
|-----|--------|
| `]t` / `[t` | Next / previous TODO comment |
| `<Leader>xt` | Show all TODOs (Trouble) |

#### Which-key [n]

| Key | Action |
|-----|--------|
| `g<CR>` | Show `g` prefix keymaps |
| `[<CR>` | Show `[` prefix keymaps |
| `]<CR>` | Show `]` prefix keymaps |

---

### Neovim Commands

| Command | Description |
|---------|-------------|
| `:Mason` | Open Mason installer UI |
| `:MasonInstall <tool>` | Install LSP/formatter/linter |
| `:ConformInfo` | Show conform.nvim formatter status |
| `:Lazy` | Open Lazy.nvim plugin manager |
| `:LazyUpdate` / `:Lazy update` | Update plugins |
| `:LazySync` | Sync plugins to lazy-lock.json |
| `:TSInstall <lang>` | Install treesitter parser |
| `:TSUpdate` | Update all parsers |
| `:Neogit` | Open Neogit |
| `:DiffviewOpen` | Open Diffview |
| `:DiffviewClose` | Close Diffview |
| `:DiffviewFileHistory %` | Current file git history |
| `:Trouble` | Open Trouble diagnostics |
| `:ToggleTerm` | Toggle terminal |
| `:ToggleTermToggleAll` | Toggle all terminals |
| `:Oil` | Open Oil file browser |
| `:Yazi` | Open Yazi file manager |
| `:Neotree toggle` | Toggle Neo-tree |
| `:WhichKey` | Show WhichKey popup |
| `:Possession{Save,Load,List}` | Session management |
| `:Translate JA` / `:Translate EN` | Translate text |
| `:TodoTrouble` | Show TODO list |
| `:CheatSheet` | Open cheatsheet |

---

*Generated by [scripts/gen-keymaps.sh](scripts/gen-keymaps.sh)*
HEREDOC

echo "Generated: ${OUTPUT}"
echo ""
echo "Core nvim keymaps (runtime):"
echo "  nvim --headless -l ${SCRIPT_DIR}/nvim-dump-keymaps.lua 2>/dev/null | head -20"
