---
- name: Install pyenv
  hosts: localhost
  become: yes
  become_user: flap1
  vars:
    bashrc_paths:
      - $HOME/.config/zsh/sh/post_load.zsh

  tasks:
    - name: Check if pyenv is already installed
      command: pyenv --version
      register: pyenv_check
      changed_when: false
      failed_when: false

    - name: Install dependencies
      apt:
        name: ['git', 'curl', 'make', 'build-essential', 'libssl-dev', 'zlib1g-dev', 'libbz2-dev', 'libreadline-dev', 'libsqlite3-dev', 'wget', 'llvm', 'libncurses5-dev', 'libncursesw5-dev', 'xz-utils', 'tk-dev', 'libffi-dev', 'liblzma-dev', 'python3-openssl']
        state: present
      when: pyenv_check is failed

    - name: Install pyenv
      git:
        repo: https://github.com/pyenv/pyenv.git
        dest: $HOME/.pyenv
        update: yes
      when: pyenv_check is failed

    - name: Check if PYENV_ROOT exists
      shell: |
        grep -q -e '^export PYENV_ROOT=' "{{ item }}"
      register: pyenv_root_check
      failed_when: false
      loop: "{{ bashrc_paths }}"
      changed_when: false

    - name: Add PYENV_ROOT to .bashrc
      blockinfile:
        path: "{{ item }}"
        block: |
          export PYENV_ROOT="$HOME/.pyenv"
          export PATH="$PYENV_ROOT/bin:$PATH"
        marker: "# {mark} AUTO-GENERATED BY ANSIBLE"
      loop: "{{ bashrc_paths }}"
      when: pyenv_root_check is failed
